export default {
    DONT_FOUND_DECKS: 'Nenhum baralho foi encontrado',
    CREATE_DECK: 'Criar baralho',
    CREATE_A_DECK: 'Criar um baralho',
    DECK_CREATOR_DECK_NAME: "Qual o nome do seu novo baralho?",
    LETS_GO_CREATE_DECK: "Vamos criar um baralho!",
    ALREADY_EXISTS_THIS_DECK_NAME: "Já existe um baralho com este nome",
    START_QUIZ: 'Vamos estudar?',
    ADD_CARD: 'Adicionar novo cartão',
    ADD_CARD_FRONT_TEXT: 'Qual é a pergunta que será feita?',
    ADD_CARD_BACK_TEXT: 'Qual é a melhor resposta para a pergunta?',
    ADD_CARD_REGISTER_BUTTON_TEXT: 'Registrar cartão',
    CARDS: 'Cartões',
    CARD: 'Cartão',
    GOT_ANSWER_CORRECT: 'Acertei',
    GOT_ANSWER_WRONG: 'Errei',
    EXCELENT: 'Excelente! que orgulho!!',
    NOT_BAD: 'Nada mal jovem gafanhoto!',
    QUIZ_CAN_BE_BETTER: 'Vamos estudar de novo? :)',
    GOT_CORRECT_ANSWER_COUNT: 'Você acertou: ',
    GOT_WRONG_ANSWER_COUNT: 'Você errou: ',
    AGAIN: 'Mais uma vez',
    CARD: 'cartão',
    CARDS: 'cartões',
    CLICK_IN_CARD_TO_FLIP: 'Clique no cartão para virar o cartão',
    BACK_TO_DECK: 'Voltar ao baralho',
    YOU_DONT_STUDIED_TODAY: 'Você não estudou hoje',
    HEY_LETS_STUDY_NOW: 'Heeey!! Vamos estudar agora?',
    QUIZ_RESULT_TITLE: 'Seu resultado',
    FILL_ALL_INPUTS: 'Necessário o preenchimento de todos os campos',
    THERE_IS_NO_CARD_REGISTERED: 'Não há cartão cadastrado',
    OPS: 'Ops!!',
    I_UNDERSTAND: 'Entendi :)'
}